# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

KeepCols <- function(df, classes, naStrings) {
    .Call('_BAST1_KeepCols', PACKAGE = 'BAST1', df, classes, naStrings)
}

KeepColsCM <- function(CM, naStrings) {
    .Call('_BAST1_KeepColsCM', PACKAGE = 'BAST1', CM, naStrings)
}

KeepColsNM <- function(NM) {
    .Call('_BAST1_KeepColsNM', PACKAGE = 'BAST1', NM)
}

cppStats <- function(id, da) {
    .Call('_BAST1_cppStats', PACKAGE = 'BAST1', id, da)
}

tabH <- function(x) {
    .Call('_BAST1_tabH', PACKAGE = 'BAST1', x)
}

tabB <- function(x) {
    .Call('_BAST1_tabB', PACKAGE = 'BAST1', x)
}

